# 作業
* 在精簡深度學習的方式上 : 卷積類神經 (CNN) 採用像素遠近，而遞歸類神經 (RNN) 採用著則是時間遠近
* 那麼，既然有著類似的設計精神，兩者是否有可能互換應用呢?

In [1]:
import numpy as np

#Input array
X = np.array([[1, 0, 1, 0], [1, 0, 1, 1], [0, 1, 0, 1]])

#Output
y = np.array([[1], [1], [0]])

X.shape, y.shape

((3, 4), (3, 1))

In [2]:
#Sigmoid Function
def sigmoid(x): 
    return  1/(1+np.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x): 
    return x*(1-x)

In [3]:
#Variable initialization
epoch = 5000 #Setting training iterations
lr = 0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set 
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

In [5]:
#weight and bias initialization
wh = np.random.uniform( size = ( inputlayer_neurons, hiddenlayer_neurons ) ) 
bh = np.random.uniform( size = ( 1, hiddenlayer_neurons ) ) 
wout = np.random.uniform( size = ( hiddenlayer_neurons, output_neurons ) ) 
bout = np.random.uniform( size = ( 1, output_neurons ) )

In [6]:
print(f'X.shape[1]= {X.shape[1]}')
print(f'wh = \n {wh}\n')
print(f'bh = \n {bh}\n')
print(f'wout = \n {wout}\n')
print(f'bout = \n {bout}\n')

X.shape[1]= 4
wh = 
 [[0.89667665 0.4311997  0.54057059]
 [0.7461075  0.23095768 0.9007663 ]
 [0.31547526 0.58869668 0.30848417]
 [0.44168409 0.7814843  0.41486917]]

bh = 
 [[0.62021031 0.94849875 0.27084822]]

wout = 
 [[0.8829767 ]
 [0.18405637]
 [0.66663699]]

bout = 
 [[0.3102976]]



### 請參閱範例中的 hidden Layer 寫法, 完成 output Layer 的程式 

In [7]:
for i in  range ( epoch ) :
    #Forward Propogation
    hidden_layer_input1 = np.dot(X, wh) 
    hidden_layer_input = hidden_layer_input1 + bh
    hiddenlayer_activations =  sigmoid( hidden_layer_input ) 
    
    output_layer_input1 = np.dot(hiddenlayer_activations, wout)
    output_layer_input = output_layer_input1 + bout
    output = sigmoid(output_layer_input)
    
print ( "output of Forward Propogation:\n{}" .format(output)) 
print ( "wout,bout of Backpropagation:\n{},\n{}" .format(wout, bout ))

output of Forward Propogation:
[[0.85012532]
 [0.8620399 ]
 [0.85614331]]
wout,bout of Backpropagation:
[[0.8829767 ]
 [0.18405637]
 [0.66663699]],
[[0.3102976]]
